### ISSUE TITLE
No module named '_sqlite3

### ISSUE THREAD

**Issue by flexformed** [vinayak-mehta/conrad#55]
HI, anyone have that issue ? how to fix that , the module  SQLITE3 was installed.... thanks

 Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-123.4.2.el7.x86_64

[user@server.com]# conrad show
Traceback (most recent call last):
  File "/usr/local/bin/conrad", line 6, in <module>
    from conrad.cli import cli
  File "/usr/local/lib/python3.7/site-packages/conrad/cli.py", line 14, in <module>
    from .db import engine, Session
  File "/usr/local/lib/python3.7/site-packages/conrad/db.py", line 42, in <module>
    configure_orm()
  File "/usr/local/lib/python3.7/site-packages/conrad/db.py", line 22, in configure_orm
    engine = create_engine(SQL_ALCHEMY_CONN, **engine_args)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/__init__.py", line 479, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 87, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 382, in dbapi
    from sqlite3 import dbapi2 as sqlite
  File "/usr/local/lib/python3.7/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/lib/python3.7/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'

**Comment by vinayak-mehta** [comment]
@flexformed What Python version are you on? https://github.com/vinayak-mehta/conrad/blob/master/CONTRIBUTING.md#bug-reports

**Comment by vinayak-mehta** [comment]
Just saw the stack trace, it's 3.7. I'll try to reproduce the error.

**Comment by flexformed** [comment]
Python 2.7.5

**Comment by vinayak-mehta** [comment]
Oh, please try using `conrad` on Python 3. Python 2 is not supported.
