### ISSUE TITLE
Conrad breaks on upgrade in Py3.7

### ISSUE THREAD

**Issue by NirantK** [vinayak-mehta/conrad#87]
Adding the stacktrace for `conrad show` here: 

```python

Traceback (most recent call last):
  File "/Users/nirant/miniconda3/envs/toys/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
    cursor, statement, parameters, context
  File "/Users/nirant/miniconda3/envs/toys/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 580, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: event.by

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/nirant/miniconda3/envs/toys/bin/conrad", line 10, in <module>
    sys.exit(cli())
  File "/Users/nirant/miniconda3/envs/toys/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/nirant/miniconda3/envs/toys/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/nirant/miniconda3/envs/toys/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/nirant/miniconda3/envs/toys/lib/python3.7/site-packages/conrad/cli.py", line 169, in invoke
    return orig_invoke(ctx)
  File "/Users/nirant/miniconda3/envs/toys/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/nirant/miniconda3/envs/toys/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/nirant/miniconda3/envs/toys/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/nirant/miniconda3/envs/toys/lib/python3.7/site-packages/conrad/cli.py", line 284, in _show
    session.query(Event).filter(*filters).order_by(Event.start_date).all()
  File "/Users/nirant/miniconda3/envs/toys/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3186, in all
    return list(self)
  File "/Users/nirant/miniconda3/envs/toys/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3342, in __iter__
    return self._execute_and_instances(context)
  File "/Users/nirant/miniconda3/envs/toys/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3367, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/Users/nirant/miniconda3/envs/toys/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/Users/nirant/miniconda3/envs/toys/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Users/nirant/miniconda3/envs/toys/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/Users/nirant/miniconda3/envs/toys/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1253, in _execute_context
    e, statement, parameters, cursor, context
  File "/Users/nirant/miniconda3/envs/toys/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1473, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/Users/nirant/miniconda3/envs/toys/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Users/nirant/miniconda3/envs/toys/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/Users/nirant/miniconda3/envs/toys/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
    cursor, statement, parameters, context
  File "/Users/nirant/miniconda3/envs/toys/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 580, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: event.by
[SQL: SELECT event.id AS event_id, event.name AS event_name, event.url AS event_url, event.city AS event_city, event.state AS event_state, event.country AS event_country, event.cfp_open AS event_cfp_open, event.cfp_end_date AS event_cfp_end_date, event.start_date AS event_start_date, event.end_date AS event_end_date, event.source AS event_source, event.tags AS event_tags, event.kind AS event_kind, event."by" AS event_by 
FROM event ORDER BY event.start_date]
(Background on this error at: http://sqlalche.me/e/e3q8)
```

**Comment by vinayak-mehta** [comment]
@NirantK Try a `conrad refresh`?

**Comment by NirantK** [comment]
This works, leaving the issue open for your reference though.

**Comment by vinayak-mehta** [comment]
This is because of a backwards incompatible change between the current and last version. Yeah, let's keep this open for anyone else who faces the same issue.

**Comment by vinayak-mehta** [comment]
Thanks for the report!

**Comment by NirantK** [comment]
Closing the issue given that it has been a while and most people using Conrad should've migrated to 3.7 by now :)
